### ISSUE TITLE
How to implement CREATE_NULL_AS_BLANK? 

### ISSUE THREAD

**Issue by lkrubner** [eaorak/excelr#2]
This is a very cool project. I'm curious how someone might invoke yet get back NULL cells? Right now I use this code that I found on StackOverflow: 

     for(Row row : sheet) {
        for(int cn=0; cn<row.getLastCellNum(); cn++) {
            // If the cell is missing from the file, generate a blank one
            // (Works by specifying a MissingCellPolicy)
            Cell cell = row.getCell(cn, Row.CREATE_NULL_AS_BLANK);
            // Print the cell for debugging
            System.out.println("CELL: " + cn + " --> " + cell.toString());
        }
     }

**Comment by enderim** [comment]
@lkrubner I had created the project a long time ago and I've realized that I had only added cell data types String and Numeric. 

Now I've added the support for all defined in POI Cell, (String, Numeric, Blank, Boolean, Error and Formula) and changed the converter interface object type from String[] to Object[] to be able to parse all. There is also a test for that which successfully gets null cell as String object. 

It should do the trick.
